apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactdash
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactdash
  template:
    metadata:
      labels:
        app: reactdash
    spec:
      containers:
      - name: reactdash
        image: percomms/reactdash:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactdash-service
spec:
  selector:
    app: reactdash
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 5500
  type: NodePort
